# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-17 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparkjob',
            name='interval_in_hours',
            field=models.IntegerField(choices=[(24, b'Daily'), (168, b'Weekly'), (720, b'Monthly')], default=24, help_text=b'Interval at which the job should run, in hours.'),
        ),
        migrations.AlterField(
            model_name='sparkjob',
            name='result_visibility',
            field=models.CharField(choices=[(b'private', b'Private: results output to an S3 bucket, viewable with AWS credentials'), (b'public', b'Public: results output to a public S3 bucket, viewable by anyone')], default=b'private', help_text=b'Whether notebook results are uploaded to a public or private bucket', max_length=50),
        ),
    ]
