# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-19 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20161017_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparkjob',
            name='identifier',
            field=models.CharField(help_text=b'Job name, used to uniqely identify individual jobs.', max_length=100, unique=True),
        ),
    ]
