# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-24 09:28
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20161019_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparkjob',
            name='emr_release',
            field=models.CharField(choices=[('5.0.0', '5.0.0'), ('4.5.0', '4.5.0')], default='5.0.0', help_text='Different EMR versions have different versions of software like Hadoop, Spark, etc', max_length=50, verbose_name='EMR release version'),
        ),
    ]
