# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-13 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_assign_more_perms'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparkjob',
            name='description',
            field=models.TextField(default=b'', help_text=b'Job description.'),
        ),
    ]
