# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-17 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_auto_20170307_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sparkjobrunalert',
            old_name='reason',
            new_name='reason_code',
        ),
        migrations.AlterField(
            model_name='sparkjobrunalert',
            name='reason_code',
            field=models.CharField(blank=True, help_text='The reason code for the creation of the alert.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sparkjobrunalert',
            name='reason_message',
            field=models.CharField(blank=True, help_text='The reason message for the creation of the alert.', max_length=50, null=True),
        ),
    ]
