# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-20 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_auto_20170317_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparkjobrunalert',
            name='reason_message',
            field=models.TextField(default='', help_text='The reason message for the creation of the alert.'),
        ),
    ]
