# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-12 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0022_sparkjobrun_emr_release_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparkjob',
            name='expired_date',
            field=models.DateTimeField(blank=True, help_text='Date/time that the job was expired.', null=True),
        ),
    ]
