# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0026_rename_terminated_final_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparkjobrun',
            name='finished_at',
            field=models.DateTimeField(blank=True, help_text='Date/time that the job was terminated or failed.', null=True),
        ),
    ]
