# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0031_update_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparkjobrun',
            name='ready_at',
            field=models.DateTimeField(blank=True, help_text='Date/time when the cluster was ready to run steps on AWS EMR.', null=True),
        ),
    ]
