# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0033_rename_scheduled_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparkjobrunalert',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='alerts', serialize=False, to='jobs.SparkJobRun'),
        ),
    ]
