# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0038_auto_20170530_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sparkjobrunalert',
            old_name='temp_id',
            new_name='id',
        ),
    ]
