# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0039_auto_20170530_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparkjobrunalert',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
