# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0040_auto_20170530_1849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sparkjobrunalert',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='sparkjobrunalert',
            unique_together=set([('run', 'reason_code', 'reason_message')]),
        ),
    ]
