# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, you can obtain one at http://mozilla.org/MPL/2.0/.
# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-15 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='emr_release',
            field=models.CharField(choices=[(b'5.0.0', b'5.0.0'), (b'4.5.0', b'4.5.0')], default=b'4.5.0', help_text=b'Different EMR versions have different versions of software like Hadoop, Spark, etc', max_length=50),
        ),
    ]
