# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, you can obtain one at http://mozilla.org/MPL/2.0/.
# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-02 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0003_cluster_master_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='master_address',
            field=models.CharField(blank=True, default=b'', help_text=b'Public address of the master node.This is only available once the cluster has bootstrapped', max_length=255),
        ),
    ]
