# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-17 09:13
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0004_auto_20161002_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='emr_release',
            field=models.CharField(choices=[('5.0.0', '5.0.0'), ('4.5.0', '4.5.0')], default='5.0.0', help_text='Different EMR versions have different versions of software like Hadoop, Spark, etc', max_length=50),
        ),
    ]
