# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-02 10:53
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0006_auto_20161024_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='most_recent_status',
            field=models.CharField(blank=True, default='', help_text='Most recently retrieved AWS status for the cluster.', max_length=50),
        ),
    ]
