# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-04 15:21
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0007_auto_20161102_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='expiration_mail_sent',
            field=models.BooleanField(default=False),
        ),
    ]
