# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-08 11:41
from django.db import migrations

from atmo.models import PermissionMigrator


def assign_cluster_view_permission(apps, schema_editor):
    Cluster = apps.get_model('clusters', 'Cluster')
    PermissionMigrator(apps, Cluster, 'view', user_field='created_by').assign()


def remove_cluster_view_permission(apps, schema_editor):
    Cluster = apps.get_model('clusters', 'Cluster')
    PermissionMigrator(apps, Cluster, 'view', user_field='created_by').remove()


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0009_auto_20161108_0933'),
        ('auth', '0007_alter_validators_add_error_messages'),
        ('guardian', '0001_initial'),
        ('contenttypes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            assign_cluster_view_permission,
            remove_cluster_view_permission,
        ),
    ]
