# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-22 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0016_auto_20170130_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='expiration_mail_sent',
            field=models.BooleanField(default=False, help_text='Whether the expiration mail were sent.'),
        ),
    ]
