# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-14 12:16
from __future__ import unicode_literals

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0018_auto_20170307_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cluster',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
