# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-29 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0024_remove_cluster_emr_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='emrrelease',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this version should be shown to the user at all.'),
        ),
    ]
