# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-30 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0025_emrrelease_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='size',
            field=models.IntegerField(help_text='Number of computers used in the cluster.'),
        ),
    ]
