# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-30 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0026_auto_20170330_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='lifetime',
            field=models.PositiveSmallIntegerField(default=8, help_text="Lifetime of the cluster after which it's automatically terminated, in hours."),
        ),
    ]
