# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0028_cluster_lifetime_extension_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='start_date',
        ),
    ]
