# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0029_remove_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cluster',
            old_name='end_date',
            new_name='expires_at',
        ),
    ]
