# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0030_rename_end_date_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='finished_at',
            field=models.DateTimeField(blank=True, help_text='Date/time when the cluster was terminated or failed.', null=True),
        ),
    ]
