# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-14 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0034_auto_20170530_1907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cluster',
            options={'permissions': [('view_cluster', 'Can view cluster'), ('maintain_cluster', 'Can maintain cluster')]},
        ),
    ]
