# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-27 15:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text=b'Worker name, used to non-uniqely identify individual workers.', max_length=100)),
                ('public_key', models.CharField(help_text=b'Public key that should be authorized for SSH access to the worker.', max_length=100000)),
                ('start_date', models.DateTimeField(blank=True, help_text=b"Date/time that the worker was started, or null if the worker isn't started yet.", null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text=b'Date/time that the worker will expire and automatically be deleted.', null=True)),
                ('instance_id', models.CharField(blank=True, help_text=b'AWS EC2 instance ID for the cluster, used for worker management.', max_length=50, null=True)),
                ('created_by', models.ForeignKey(help_text=b'User that created the worker instance.', on_delete=django.db.models.deletion.CASCADE, related_name='worker_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
