# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-16 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0002_assign_view_perms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sshkey',
            name='fingerprint',
            field=models.CharField(blank=True, max_length=48),
        ),
        migrations.AlterUniqueTogether(
            name='sshkey',
            unique_together=set([('created_by', 'fingerprint')]),
        ),
    ]
